### ISSUE TITLE
Duplicate check

### ISSUE THREAD

**Issue by JulianDroste** [J4YB3/discord-movie-night-bot#5]
**AS A** Watchparty Creator
**I WANT TO** guarantee that a movie does not get inserted into the watchlist twice
**SO THAT** no film is prioritized over one another

**Comment by J4YB3** [comment]
## Description
_**As a**_  User 
_**I want**_  be informed that a movie is already in the database
_**so that**_ we don't have duplicate movies

## Acceptance Criteria
- [ ] Check for similar movie titles that are already in the database
- [ ] Show the user all possible matches and ask if the entered movie is among them
- [ ] Add the movie or scrap it based on the users answer
